[project]
name = "django-blog"
version = "0.1.0"
description = "My Blog App"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
]

[dependency-groups]
dev = [
    "ruff>=0.12.3",
]
